name: sof_tracker
description: "A sleek app for browsing StackOverflow users, tracking their reputation, and bookmarking favorite profiles."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # Core
  get: ^4.6.6
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # API
  data_channel: ^2.0.0+1
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  dio_smart_retry: ^6.0.0
  retrofit: ^4.4.0

  # Localization
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # Logger
  talker: ^4.4.1
  talker_flutter: ^4.4.1
  talker_dio_logger: ^4.4.1

  # Icons
  fluentui_system_icons: ^1.1.255
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

  # Utils
  envied: ^0.5.4+1
  flex_color_scheme: ^7.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.3
  internet_connection_checker_plus: ^2.5.1
  cached_network_image: ^3.4.1
  infinite_scroll_pagination: ^4.0.0
  flutter_animate: ^4.5.0
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  ndialog: ^4.3.1
  shimmer: ^3.0.0
  rxdart: ^0.28.0
  jiffy: ^6.3.1

  # UI
  animated_bottom_navigation_bar: ^1.3.3
  another_flutter_splash_screen: ^1.2.1
  gap: ^3.0.1
  loading_animation_widget: ^1.2.1
  badges: ^3.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.12
  envied_generator: ^0.5.4+1
  flutter_gen_runner: ^5.7.0
  freezed: ^2.5.7
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/images/
    - assets/svgs/
    - assets/lotties/

# Localization
flutter_intl:
  enabled: true
  class_name: I10n
  arb_dir: assets/translations
  output_dir: lib/app/global/localization

# Resources
flutter_gen:
  output: lib/app/global/constants/resources/
  integrations:
    flutter_svg: true
    lottie: true

# Launcher icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/sof_logo.png"
  min_sdk_android: 21

# Splash screen
flutter_native_splash:
  color: '#FFFFFF'
  image: 'assets/images/sof_logo.png'
  android_12:
    color: '#FFFFFF'
    image: 'assets/images/sof_logo.png'